### ISSUE TITLE
Can you do me a favor please.

### ISSUE THREAD

**Issue by Brianwind** [Freddd13/autoscore#1]
在我发现这个repo之前，我已经错过了几个谱子了（哭），所以我想问问是否可以拜托你把最近败犬女主的几个谱子发给我

打扰了！如果不行的话就直接关闭这个issue吧

**Comment by Brianwind** [comment]
细看了一下代码和readme，请问下载的文件是下载到哪里的呢？代码里似乎提到cloudreve，但是没有输入cloudreve信息的地方；
另外，我还想问一下下载策略，是只下载当天的sheet吗？因为我今天跑了一下，目前还在免费期的败犬女主ED3并没有开始下载，而且log里面提示Nothing new

**Comment by Freddd13** [comment]
啊哈哈，居真有人用了。由于是自用，目前下载策略比较简陋，大概是通过github action存记一个sheet号，这个号目前是递增的所以如果读到小等于下载过的我就认为没新谱子。

**Comment by Freddd13** [comment]
@Brianwind 其中_last_download_signal记录的是上次下载的谱子号，你下载nothing new是因为现在仓库里的这个文件记录的是我的，我已经下到最新的了，你只要把他清空就好了

**Comment by Freddd13** [comment]
@Brianwind 至于下到哪里，我自己是有个OneDrive 企业版，我建了一个app用api直接存到里面，但是我不清楚普通版有没有方法存，大概得用rclone才能达到目的（我还有个b站备份收藏夹的仓库就是用的rclone存，参考pybilibackup）。如果你没有OneDrive 的条件，有两种获取谱子的方法，一种是新谱子会作为附件发到邮件里面，不过可能会过期？另一种就是你把.gitignore 的files取消掉 下的谱子一般存在files下，这样你就能把谱子更新到你的仓库/files 下面，不过这个我测试过。 至于cloudreve，这里暂时没有使用，这套代码是从我另一个下载项目粘过来的改的，因为基本逻辑是一样的。

**Comment by Freddd13** [comment]
@Brianwind 给我发个邮箱，我可以把项目开始运行后这几个月的谱子都分享给你

**Comment by Freddd13** [comment]
@Brianwind 其实最近还发现一个问题，最近收到mms的邮件，大概是halcyon 似乎在上传后修改了谱子，谱子有更新。我猜可能是修正了一点错误之类的，但代码目前没处理这种情况，一个谱子我就下了一次，后面有时间会改进

**Comment by Brianwind** [comment]
感谢！请发到这个邮箱：lengbrian@163.com
其他的配置我回去之后再看看。

**Comment by Freddd13** [comment]
已发送
